name: CI/CD Pipeline for Laravel

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up PHP with required extensions
    - name: Set up PHP
      uses: shivammathur/setup-php@v3
      with:
        php-version: '8.1'
        extensions: mbstring, pdo, openssl

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        composer install
        cp .env.example .env
        php artisan key:generate

    # Step 4: Run Laravel tests (optional)
    - name: Run tests
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Deploy to server using SSH
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.11
      with:
        host: your-server-ip
        username: your-username
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          cd /path/to/your/project
          git pull origin develop
          composer install
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:cache
